language: java
jdk:
  - openjdk8
  - openjdk11

services:
  - mysql
  -
before_install:
  - mysql -e 'CREATE DATABASE test;'

env:
  - username=travis
  - password=
  - jdbcUrl=jdbc:mysql://127.0.0.1:3306/test